### ISSUE TITLE
RMS = 1 of 32bit int signal

### ISSUE THREAD

**Issue by maxamazing** [m-r-s/fade#7]
in the ReadMe:

_"Please note that FADE expects recordings to be 32-bit signed-integer wav files that are calibrated such that an RMS of 1 means 130 dB SPL."_

shouldn't it be 

_"Please note that FADE expects recordings to be 32-bit signed-integer wav files that are calibrated such that an RMS of 0 dB FS means 130 dB SPL."_

because a RMS =1 of a 32-bit integer signal is quite small.

**Comment by m-r-s** [comment]
Usually, the available integer bits are used to encode values in the interval [-1 1].
As far as I know, values outside that range are only possible with floating point encoding.
Maybe I am wrong.
Are there really audio-file libraries which load 32bit signed integer without normalization?

**Comment by m-r-s** [comment]
Okay, thanks! I wasn't aware of that behavior. Fixed with 8cad074283eb31e96177a0b75de2511919493d3c
